extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  # Data source: traces
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:

exporters:
  # Data source: traces
  logging:
    loglevel: debug
  
  zipkin:
    endpoint: "http://127.0.0.1:9412/api/v2/spans"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin]
  extensions: [health_check, pprof, zpages]