extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  # Data source: metrics
  opencensus:

processors:
  batch:

exporters:
  # Data source: metrics
  logging:
    loglevel: debug


service:

  pipelines:

    metrics:
      receivers: [opencensus]
      processors: [batch]
      exporters: [logging]

  extensions: [health_check, pprof, zpages]
